module.exports = {
    customSyntax: 'postcss-scss',
    plugins: [
        'stylelint-scss',
        'stylelint-order',
    ],
    rules: {
        'color-hex-case': 'lower',
        'color-hex-length': 'long',
        'color-named': 'never',
        'color-no-invalid-hex': true,
        'font-family-name-quotes': 'always-where-recommended',
        'font-weight-notation': 'named-where-possible',
        'function-calc-no-unspaced-operator': true,
        'function-comma-newline-after': 'always-multi-line',
        'function-comma-space-after': 'always',
        'function-linear-gradient-no-nonstandard-direction': true,
        'function-max-empty-lines': 0,
        'function-name-case': 'lower',
        'function-parentheses-space-inside': 'never',
        'function-whitespace-after': 'always',
        'number-no-trailing-zeros': true,
        'string-no-newline': true,
        'string-quotes': 'single',
        'length-zero-no-unit': true,
        'unit-case': 'lower',
        'unit-no-unknown': true,
        'value-keyword-case': 'lower',
        'value-list-comma-newline-after': 'always-multi-line',
        'value-list-comma-space-after': 'always',
        'shorthand-property-no-redundant-values': true,
        'property-case': 'lower',
        'property-no-unknown': [
            true,
            {
                ignoreProperties: ['gap'],
            },
        ],
        'declaration-bang-space-before': 'always',
        'declaration-no-important': true,
        'declaration-block-no-duplicate-properties': true,
        'declaration-block-no-shorthand-property-overrides': true,
        'order/properties-order':  [
            [
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        'position',
                        'z-index',
                        'top',
                        'right',
                        'bottom',
                        'left',
                    ],
                },
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        'display',
                        'visibility',
                        'float',
                        'clear',
                        'overflow',
                        'overflow-x',
                        'overflow-y',
                        '-ms-overflow-x',
                        '-ms-overflow-y',
                        '-webkit-overflow-scrolling',
                        'clip',
                        'zoom',
                        'flex',
                        'flex-direction',
                        'flex-order',
                        'flex-pack',
                        'flex-align',
                    ],
                },
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        '-webkit-box-sizing',
                        '-moz-box-sizing',
                        'box-sizing',
                        'width',
                        'min-width',
                        'max-width',
                        'height',
                        'min-height',
                        'max-height',
                        'margin',
                        'margin-top',
                        'margin-right',
                        'margin-bottom',
                        'margin-left',
                        'padding',
                        'padding-top',
                        'padding-right',
                        'padding-bottom',
                        'padding-left',
                    ],
                },
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        'table-layout',
                        'empty-cells',
                        'caption-side',
                        'border-spacing',
                        'border-collapse',
                        'list-style',
                        'list-style-position',
                        'list-style-type',
                        'list-style-image',
                    ],
                },
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        'content',
                        'quotes',
                        'counter-reset',
                        'counter-increment',
                        'resize',
                        'cursor',
                        '-webkit-user-select',
                        '-moz-user-select',
                        '-ms-user-select',
                        'user-select',
                        'nav-index',
                        'nav-up',
                        'nav-right',
                        'nav-down',
                        'nav-left',
                        '-webkit-transition',
                        '-moz-transition',
                        '-ms-transition',
                        '-o-transition',
                        'transition',
                        '-webkit-transition-delay',
                        '-moz-transition-delay',
                        '-ms-transition-delay',
                        '-o-transition-delay',
                        'transition-delay',
                        '-webkit-transition-timing-function',
                        '-moz-transition-timing-function',
                        '-ms-transition-timing-function',
                        '-o-transition-timing-function',
                        'transition-timing-function',
                        '-webkit-transition-duration',
                        '-moz-transition-duration',
                        '-ms-transition-duration',
                        '-o-transition-duration',
                        'transition-duration',
                        '-webkit-transition-property',
                        '-moz-transition-property',
                        '-ms-transition-property',
                        '-o-transition-property',
                        'transition-property',
                        '-webkit-transform',
                        '-moz-transform',
                        '-ms-transform',
                        '-o-transform',
                        'transform',
                        '-webkit-transform-origin',
                        '-moz-transform-origin',
                        '-ms-transform-origin',
                        '-o-transform-origin',
                        'transform-origin',
                        '-webkit-animation',
                        '-moz-animation',
                        '-ms-animation',
                        '-o-animation',
                        'animation',
                        '-webkit-animation-name',
                        '-moz-animation-name',
                        '-ms-animation-name',
                        '-o-animation-name',
                        'animation-name',
                        '-webkit-animation-duration',
                        '-moz-animation-duration',
                        '-ms-animation-duration',
                        '-o-animation-duration',
                        'animation-duration',
                        '-webkit-animation-play-state',
                        '-moz-animation-play-state',
                        '-ms-animation-play-state',
                        '-o-animation-play-state',
                        'animation-play-state',
                        '-webkit-animation-timing-function',
                        '-moz-animation-timing-function',
                        '-ms-animation-timing-function',
                        '-o-animation-timing-function',
                        'animation-timing-function',
                        '-webkit-animation-delay',
                        '-moz-animation-delay',
                        '-ms-animation-delay',
                        '-o-animation-delay',
                        'animation-delay',
                        '-webkit-animation-iteration-count',
                        '-moz-animation-iteration-count',
                        '-ms-animation-iteration-count',
                        '-o-animation-iteration-count',
                        'animation-iteration-count',
                        '-webkit-animation-direction',
                        '-moz-animation-direction',
                        '-ms-animation-direction',
                        '-o-animation-direction',
                        'animation-direction',
                        'text-align',
                        '-webkit-text-align-last',
                        '-moz-text-align-last',
                        '-ms-text-align-last',
                        'text-align-last',
                        'vertical-align',
                        'white-space',
                        'text-decoration',
                        'text-emphasis',
                        'text-emphasis-color',
                        'text-emphasis-style',
                        'text-emphasis-position',
                        'text-indent',
                        '-ms-text-justify',
                        'text-justify',
                        'text-transform',
                        'letter-spacing',
                        'word-spacing',
                        '-ms-writing-mode',
                        'text-outline',
                        'text-transform',
                        'text-wrap',
                        'text-overflow',
                        '-ms-text-overflow',
                        'text-overflow-ellipsis',
                        'text-overflow-mode',
                        '-ms-word-wrap',
                        'word-wrap',
                        'word-break',
                        '-ms-word-break',
                        '-moz-tab-size',
                        '-o-tab-size',
                        'tab-size',
                        '-webkit-hyphens',
                        '-moz-hyphens',
                        'hyphens',
                        'pointer-events',
                    ],
                },
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        'opacity',
                        'filter:progid:DXImageTransform.Microsoft.Alpha(Opacity',
                        '-ms-filter:\\\'progid:DXImageTransform.Microsoft.Alpha',
                        '-ms-interpolation-mode',
                        'color',
                        'border',
                        'border-collapse',
                        'border-width',
                        'border-style',
                        'border-color',
                        'border-top',
                        'border-top-width',
                        'border-top-style',
                        'border-top-color',
                        'border-right',
                        'border-right-width',
                        'border-right-style',
                        'border-right-color',
                        'border-bottom',
                        'border-bottom-width',
                        'border-bottom-style',
                        'border-bottom-color',
                        'border-left',
                        'border-left-width',
                        'border-left-style',
                        'border-left-color',
                        '-webkit-border-radius',
                        '-moz-border-radius',
                        'border-radius',
                        '-webkit-border-top-left-radius',
                        '-moz-border-radius-topleft',
                        'border-top-left-radius',
                        '-webkit-border-top-right-radius',
                        '-moz-border-radius-topright',
                        'border-top-right-radius',
                        '-webkit-border-bottom-right-radius',
                        '-moz-border-radius-bottomright',
                        'border-bottom-right-radius',
                        '-webkit-border-bottom-left-radius',
                        '-moz-border-radius-bottomleft',
                        'border-bottom-left-radius',
                        '-webkit-border-image',
                        '-moz-border-image',
                        '-o-border-image',
                        'border-image',
                        '-webkit-border-image-source',
                        '-moz-border-image-source',
                        '-o-border-image-source',
                        'border-image-source',
                        '-webkit-border-image-slice',
                        '-moz-border-image-slice',
                        '-o-border-image-slice',
                        'border-image-slice',
                        '-webkit-border-image-width',
                        '-moz-border-image-width',
                        '-o-border-image-width',
                        'border-image-width',
                        '-webkit-border-image-outset',
                        '-moz-border-image-outset',
                        '-o-border-image-outset',
                        'border-image-outset',
                        '-webkit-border-image-repeat',
                        '-moz-border-image-repeat',
                        '-o-border-image-repeat',
                        'border-image-repeat',
                        'outline',
                        'outline-width',
                        'outline-style',
                        'outline-color',
                        'outline-offset',
                        'background',
                        'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader',
                        'background-color',
                        'background-image',
                        'background-repeat',
                        'background-attachment',
                        'background-position',
                        'background-position-x',
                        '-ms-background-position-x',
                        'background-position-y',
                        '-ms-background-position-y',
                        '-webkit-background-clip',
                        '-moz-background-clip',
                        'background-clip',
                        'background-origin',
                        '-webkit-background-size',
                        '-moz-background-size',
                        '-o-background-size',
                        'background-size',
                        'box-decoration-break',
                        '-webkit-box-shadow',
                        '-moz-box-shadow',
                        'box-shadow',
                        'filter:progid:DXImageTransform.Microsoft.gradient',
                        '-ms-filter:\\\'progid:DXImageTransform.Microsoft.gradient',
                        'text-shadow',
                    ],
                },
                {
                    'emptyLineBefore': 'always',
                    'order': 'strict',
                    'properties': [
                        'font',
                        'font-family',
                        'font-size',
                        'font-weight',
                        'font-style',
                        'font-variant',
                        'font-size-adjust',
                        'font-stretch',
                        'font-effect',
                        'font-emphasize',
                        'font-emphasize-position',
                        'font-emphasize-style',
                        'font-smooth',
                        'line-height',
                    ],
                },
            ],
        ],
        'declaration-block-semicolon-newline-after': 'always',
        'declaration-colon-space-after': 'always',
        'declaration-colon-space-before': 'never',
        'block-opening-brace-newline-after': 'always-multi-line',
        'block-opening-brace-newline-before': 'always-multi-line',
        'block-closing-brace-newline-after': 'always',
        'block-no-empty': true,
        'selector-attribute-brackets-space-inside': 'never',
        'selector-combinator-space-after': 'always',
        'selector-combinator-space-before': 'always',
        'selector-max-universal': 0,
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-class-no-unknown': [true, {
            'ignorePseudoClasses': ['global'],
        }],
        'selector-pseudo-class-parentheses-space-inside': 'never',
        'selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'single',
        'selector-pseudo-element-no-unknown': true,
        'selector-type-case': 'lower',
        'selector-type-no-unknown': true,
        'selector-max-empty-lines': 0,
        'selector-list-comma-newline-after': 'always',
        'selector-list-comma-space-after': 'always-single-line',
        'rule-empty-line-before': [
            'always',
            {
                'except': ['first-nested'],
                'ignore': ['after-comment'],
            },
        ],
        'media-feature-colon-space-after': 'always',
        'media-feature-colon-space-before': 'never',
        'media-feature-name-case': 'lower',
        'media-feature-parentheses-space-inside': 'never',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-range-operator-space-before': 'always',
        'media-query-list-comma-newline-after': 'always-multi-line',
        'media-query-list-comma-space-after': 'always-single-line',
        'at-rule-empty-line-before': [
            'always',
            {
                'except': ['first-nested', 'blockless-after-same-name-blockless'],
                'ignore': ['after-comment'],
                'ignoreAtRules': ['else', 'include'],
            },
        ],
        'at-rule-name-case': 'lower',
        'at-rule-name-space-after': 'always',
        'at-rule-semicolon-newline-after': 'always',
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',
        'indentation': 4,
        'max-empty-lines': 1,
        'no-duplicate-selectors': true,
        'no-empty-source': true,
        'no-eol-whitespace': true,
        'no-extra-semicolons': true,
        'no-invalid-double-slash-comments': true,
        'no-missing-end-of-source-newline': true,
    },
};
